name 'methylation'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures methylation'
long_description 'Installs/Configures methylation'
version '0.1.0'
